// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/yuvi/YuviOS.tsx": () => import("../components/mockups/yuvi/YuviOS.tsx"),
  "./components/mockups/yuvi/components/AddLeadModal.tsx": () => import("../components/mockups/yuvi/components/AddLeadModal.tsx"),
  "./components/mockups/yuvi/components/AITeamView.tsx": () => import("../components/mockups/yuvi/components/AITeamView.tsx"),
  "./components/mockups/yuvi/components/ApprovalsView.tsx": () => import("../components/mockups/yuvi/components/ApprovalsView.tsx"),
  "./components/mockups/yuvi/components/CallModal.tsx": () => import("../components/mockups/yuvi/components/CallModal.tsx"),
  "./components/mockups/yuvi/components/ChatView.tsx": () => import("../components/mockups/yuvi/components/ChatView.tsx"),
  "./components/mockups/yuvi/components/ClientsView.tsx": () => import("../components/mockups/yuvi/components/ClientsView.tsx"),
  "./components/mockups/yuvi/components/DashboardView.tsx": () => import("../components/mockups/yuvi/components/DashboardView.tsx"),
  "./components/mockups/yuvi/components/KnowledgeBaseView.tsx": () => import("../components/mockups/yuvi/components/KnowledgeBaseView.tsx"),
  "./components/mockups/yuvi/components/LeadDetailModal.tsx": () => import("../components/mockups/yuvi/components/LeadDetailModal.tsx"),
  "./components/mockups/yuvi/components/LeadsView.tsx": () => import("../components/mockups/yuvi/components/LeadsView.tsx"),
  "./components/mockups/yuvi/components/PipelineView.tsx": () => import("../components/mockups/yuvi/components/PipelineView.tsx"),
  "./components/mockups/yuvi/components/ReportsView.tsx": () => import("../components/mockups/yuvi/components/ReportsView.tsx"),
  "./components/mockups/yuvi/components/SettingsView.tsx": () => import("../components/mockups/yuvi/components/SettingsView.tsx"),
  "./components/mockups/yuvi/components/ui.tsx": () => import("../components/mockups/yuvi/components/ui.tsx")
};
